add payment UI
yijia-cc/grouplive pull request #45
Opened 2021-05-25 00:55 UTC by Zanzan666

2021-05-25 02:45 UTC, wl328Weiminli commented on web/src/pages/Payment/index.jsx
> +
```suggestion 

```

2021-05-25 02:46 UTC, wl328Weiminli commented on web/src/pages/Payment/index.jsx
> +
```suggestion
        
```

2021-05-25 02:46 UTC, wl328Weiminli commented on web/src/pages/Payment/index.jsx
> +
```suggestion
        
```

2021-05-25 02:49 UTC, wl328Weiminli commented on web/src/index.js
> +import 'bootstrap/dist/js/bootstrap.min.js';
```suggestion
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/js/bootstrap.min.js';
import App from "./App";
import reportWebVitals from "./reportWebVitals";
```

2021-05-25 02:53 UTC, wl328Weiminli commented on web/src/index.js
> +import 'bootstrap/dist/js/bootstrap.min.js';
@Zanzan666  😠 Third-party package should put before our component

2021-05-26 05:51 UTC, yijia-cc requested changes
Hi @Zanzan666, thank you so much for working on this feature. Please address @wl328Weiminli 's comments.

2021-06-01 00:36 UTC, closed without merging